### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by shahizat** [espnet/espnet_onnx#77]
Hi,

Could you please help me with bellow issue, when I want to export TTS model using export_from_zip? Thanks in advance!
`Traceback (most recent call last):
  File "convert_to_onnx.py", line 18, in <module>
    m.export_from_zip(
  File "/home/jetson/.virtualenvs/espnet2/lib/python3.8/site-packages/espnet_onnx/export/tts/export_tts.py", line 119, in export_from_zip
    self.export(model, tag_name, quantize)
  File "/home/jetson/.virtualenvs/espnet2/lib/python3.8/site-packages/espnet_onnx/export/tts/export_tts.py", line 60, in export
    model_config = self._create_config(model, export_dir)
  File "/home/jetson/.virtualenvs/espnet2/lib/python3.8/site-packages/espnet_onnx/export/tts/export_tts.py", line 127, in _create_config
    ret.update(get_preprocess_config(model.preprocess_fn, path))
  File "/home/jetson/.virtualenvs/espnet2/lib/python3.8/site-packages/espnet_onnx/export/tts/get_config.py", line 47, in get_preprocess_config
    'cleaner_types': model.text_cleaner.cleaner_types[0]
IndexError: list index out of range
`

**Comment by Ht-zhang-xianyu** [comment]
same problem
