### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zyb8543d** [espnet/espnet_onnx#79]
export codes:
```
from espnet2.bin.tts_inference import Text2Speech
from espnet_onnx.export import TTSModelExport

m = TTSModelExport()

# download with espnet_model_zoo and export from pretrained model
m.export_from_pretrained('kan-bayashi/csmsc_tts_train_conformer_fastspeech2_raw_phn_pypinyin_g2p_phone_train.loss.ave', quantize=True)

# export from trained model
text2speech = Text2Speech(args)
m.export(text2speech, 'kan-bayashi/csmsc_tts_train_conformer_fastspeech2_raw_phn_pypinyin_g2p_phone_train.loss.ave', quantize=True)
```

error:
```
WARNING:root:Fallback to conformer_pos_enc_layer_type = 'legacy_rel_pos' due to the compatibility. If you want to use the new one, please use conformer_pos_enc_layer_type = 'latest'.
WARNING:root:Fallback to conformer_self_attn_layer_type = 'legacy_rel_selfattn' due to the compatibility. If you want  to use the new one, please use conformer_pos_enc_layer_type = 'latest'.
Traceback (most recent call last):
  File "export_espnet_tts.py", line 7, in <module>
    m.export_from_pretrained('kan-bayashi/csmsc_tts_train_conformer_fastspeech2_raw_phn_pypinyin_g2p_phone_train.loss.ave', quantize=True)
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/site-packages/espnet_onnx-0.1.10-py3.8.egg/espnet_onnx/export/tts/export_tts.py", line 114, in export_
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/site-packages/espnet_onnx-0.1.10-py3.8.egg/espnet_onnx/export/tts/export_tts.py", line 127, in _create_config
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/site-packages/espnet_onnx-0.1.10-py3.8.egg/espnet_onnx/export/tts/get_co
```

**Comment by Masao-Someki** [comment]
Hi @v-yunbin ,
I fixed the issue with #77, so would you try this again and check if your issue is fixed?
