### ISSUE TITLE
 Speech2Text.__init__() got an unexpected keyword argument 'train_config' when downloading model

### ISSUE THREAD

**Issue by ADD-eNavarro** [espnet/espnet_onnx#82]
Hi there.

I am using this code, stright from the usage section:
```
from espnet2.bin.asr_inference import Speech2Text
from espnet_onnx.export import ASRModelExport

m = ASRModelExport()

# download with espnet_model_zoo and export from pretrained model
m.export_from_pretrained('espnet/kan-bayashi_vctk_full_band_multi_spk_vits', quantize=True)
```

And getting this result:

```
Downloading (…)de1ff/.gitattributes: 100%|████████████████████████████████████████████████| 1.18k/1.18k [00:00<?, ?B/s]
Downloading (…)7a4efde1ff/README.md: 100%|████████████████████████████████████████████████| 1.91k/1.91k [00:00<?, ?B/s]
Downloading (…)rg/tr_no_dev/spk2sid: 100%|████████████████████████████████████████████████████| 872/872 [00:00<?, ?B/s]
Downloading (…)no_space/config.yaml: 100%|████████████████████████████████████████████████| 8.23k/8.23k [00:00<?, ?B/s]
Downloading (…)or_backward_time.png: 100%|█████████████████████████████████████████| 33.1k/33.1k [00:00<00:00, 353kB/s]
Downloading (…)scriminator_loss.png: 100%|█████████████████████████████████████████| 45.5k/45.5k [00:00<00:00, 486kB/s]
Downloading (…)tor_forward_time.png: 100%|█████████████████████████████████████████| 32.4k/32.4k [00:00<00:00, 346kB/s]
Downloading (…)inator_fake_loss.png: 100%|█████████████████████████████████████████| 59.9k/59.9k [00:00<00:00, 640kB/s]
Downloading (…)_optim_step_time.png: 100%|█████████████████████████████████████████| 59.7k/59.7k [00:00<00:00, 637kB/s]
Downloading (…)nator_train_time.png: 100%|█████████████████████████████████████████| 28.7k/28.7k [00:00<00:00, 307kB/s]
Downloading (…)nerator_adv_loss.png: 100%|█████████████████████████████████████████| 59.5k/59.5k [00:00<00:00, 476kB/s]
Downloading (…)inator_real_loss.png: 100%|█████████████████████████████████████████| 60.4k/60.4k [00:00<00:00, 322kB/s]
Downloading (…)or_backward_time.png: 100%|█████████████████████████████████████████| 30.1k/30.1k [00:00<00:00, 321kB/s]
Downloading (…)nerator_dur_loss.png: 100%|█████████████████████████████████████████| 42.3k/42.3k [00:00<00:00, 451kB/s]
Downloading (…)tor_forward_time.png: 100%|█████████████████████████████████████████| 54.0k/54.0k [00:00<00:00, 494kB/s]
Downloading (…)_feat_match_loss.png: 100%|█████████████████████████████████████████| 40.1k/40.1k [00:00<00:00, 427kB/s]
Downloading (…)rator_train_time.png: 100%|█████████████████████████████████████████| 31.0k/31.0k [00:00<00:00, 283kB/s]
Downloading (…)ax_cached_mem_GB.png: 100%|█████████████████████████████████████████| 28.9k/28.9k [00:00<00:00, 231kB/s]
Downloading (…)images/iter_time.png: 100%|█████████████████████████████████████████| 57.1k/57.1k [00:00<00:00, 406kB/s]
Downloading (…)s/generator_loss.png: 100%|█████████████████████████████████████████| 28.7k/28.7k [00:00<00:00, 102kB/s]
Downloading (…)_optim_step_time.png: 100%|█████████████████████████████████████████| 56.8k/56.8k [00:00<00:00, 298kB/s]
Downloading (…)nerator_mel_loss.png: 100%|█████████████████████████████████████████| 30.9k/30.9k [00:00<00:00, 165kB/s]
Downloading (…)enerator_kl_loss.png: 100%|████████████████████████████████████████| 23.4k/23.4k [00:00<00:00, 83.1kB/s]
Downloading (…)mages/optim0_lr0.png: 100%|█████████████████████████████████████████| 25.2k/25.2k [00:00<00:00, 269kB/s]
Downloading (…)7a4efde1ff/meta.yaml: 100%|████████████████████████████████████████████████████| 360/360 [00:00<?, ?B/s]
Downloading (…)mages/train_time.png: 100%|█████████████████████████████████████████| 29.1k/29.1k [00:00<00:00, 310kB/s]
Downloading (…)mages/optim1_lr0.png: 100%|█████████████████████████████████████████| 25.0k/25.0k [00:00<00:00, 266kB/s]
Downloading (…)count.ave_10best.pth: 100%|██████████████████████████████████████████| 387M/387M [01:50<00:00, 3.49MB/s]
Fetching 28 files: 100%|███████████████████████████████████████████████████████████████| 28/28 [01:54<00:00,  4.10s/it]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Enrique.Navarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\espnet_onnx\export\asr\export_asr.py", line 176, in export_from_pretrained
    model = Speech2Text.from_pretrained(tag_name, **pretrained_config)
  File "C:\Users\Enrique.Navarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\espnet2\bin\asr_inference.py", line 516, in from_pretrained
    return Speech2Text(**kwargs)
TypeError: Speech2Text.__init__() got an unexpected keyword argument 'train_config'
>>> speech2text = Speech2Text(args)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'args' is not defined
```

**Comment by Masao-Someki** [comment]
Hi @ADD-eNavarro, you seem to be trying to export the TTS model, so please use `TTSModelExport`.

```python
from espnet_onnx.export import TTSModelExport

m = TTSModelExport()

m.export_from_pretrained('espnet/kan-bayashi_vctk_full_band_multi_spk_vits', quantize=True)
```

**Comment by ADD-eNavarro** [comment]
Thanks, I see that my ignorance on the library was the issue. 
I imported the TTSModelExport now as you said, but then:

```
>>> from espnet_onnx.export import TTSModelExport
>>> m = TTSModelExport()
>>> m.export_from_pretrained('espnet/kan-bayashi_vctk_full_band_multi_spk_vits', quantize=True)
Fetching 28 files: 100%|█████████████████████████████████████████████████████████████| 28/28 [00:00<00:00, 4680.21it/s]
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\espnet2\gan_tts\vits\monotonic_align\__init__.py:19: UserWarning: Cython version is not available. Fallback to 'EXPERIMETAL' numba version. If you want to use the cython version, please build it as follows: `cd espnet2/gan_tts/vits/monotonic_align; python setup.py build_ext --inplace`
  warnings.warn(
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\torch\onnx\utils.py:2036: UserWarning: Provided key feats for dynamic axes is not a valid input/output name
  warnings.warn(
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\torch\onnx\utils.py:2036: UserWarning: Provided key duration for dynamic axes is not a valid input/output name
  warnings.warn(
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\espnet2\gan_tts\vits\transform.py:116: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if torch.min(inputs) < left or torch.max(inputs) > right:
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\espnet2\gan_tts\vits\transform.py:121: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if min_bin_width * num_bins > 1.0:
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\espnet2\gan_tts\vits\transform.py:123: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if min_bin_height * num_bins > 1.0:
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\espnet2\gan_tts\vits\transform.py:173: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (discriminant >= 0).all()
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\torch\onnx\_internal\jit_utils.py:258: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\torch\onnx\_internal\jit_utils.py:258: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at ..\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\torch\onnx\utils.py:687: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at ..\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  _C._jit_pass_onnx_graph_shape_type_inference(
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\torch\onnx\utils.py:687: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_graph_shape_type_inference(
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\torch\onnx\utils.py:1178: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at ..\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  _C._jit_pass_onnx_graph_shape_type_inference(
C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\torch\onnx\utils.py:1178: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_graph_shape_type_inference(
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.0/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.0/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.0/self_attn/MatMul_2]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.1/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.1/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.1/self_attn/MatMul_2]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.2/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.2/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.2/self_attn/MatMul_2]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.3/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.3/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.3/self_attn/MatMul_2]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.4/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.4/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.4/self_attn/MatMul_2]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.5/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.5/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/generator/text_encoder/encoder/encoders/encoders.5/self_attn/MatMul_2]
Ignore MatMul due to non constant B: /[/generator/MatMul_1]
Ignore MatMul due to non constant B: /[/generator/MatMul]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\espnet_onnx\export\tts\export_tts.py", line 114, in export_from_pretrained
    self.export(model, tag_name, quantize)
  File "C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\espnet_onnx\export\tts\export_tts.py", line 85, in export
    qt_config = self._quantize_model(export_dir, quantize_dir, verbose)
  File "C:\Users\eNavarro\Desktop\Pruebas_TTS\espnet_onnx\env_espnet\lib\site-packages\espnet_onnx\export\tts\export_tts.py", line 200, in _quantize_model
    os.remove(os.path.join(model_from, basename + '-opt.onnx'))
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\eNavarro\\.cache\\espnet_onnx\\espnet\\kan-bayashi_vctk_full_band_multi_spk_vits\\full\\vits-opt.onnx'
```
In the path pointed by the error there's a vits.onnx file, but not vits-opt.onnx. 
There's a "quantize" folder next to the "full" folder, containing a vits_qt.onnx file, both can be opened with Netron correctly.
So after looking into export_tts.py, the failing line is the one-to-last, I believe it's failing to delete a temporal file (which is not there any more, or never was) but the exportation is happening correctly. 
You may want to take a look at that line though, just to have an error-free process.

**Comment by Masao-Someki** [comment]
I realized this bug recently and fixed it. This will be included in the next release.
https://github.com/espnet/espnet_onnx/blob/0d666f5f13e221e7c5945730a034100cfb6b19d2/espnet_onnx/export/tts/export_tts.py#L190-L192

Quantization is not applied to the conv layer, so the model size doesn't become half of the full model.

**Comment by ADD-eNavarro** [comment]
Awesome, thank you so much!
