### ISSUE TITLE
ModuleNotFoundError: No module named 'espnet_model_zoo.downloader'; 'espnet_model_zoo' is not a package

### ISSUE THREAD

**Issue by neso613** [espnet/espnet_onnx#93]
Trying to download the pretrained model using following code -

`from espnet2.bin.asr_inference import Speech2Text
from espnet_onnx.export import ASRModelExport

m = ASRModelExport()

tag_name = 'asr_train_asr_transformer2_raw_zh_char_batch_bins20000000_ctc_confignore_nan_gradtrue_sp_valid.acc.ave'

##### download with espnet_model_zoo and export from pretrained model
m.export_from_pretrained(tag_name, quantize=True)

#####  export from trained model
speech2text = Speech2Text(args)
m.export(speech2text, '<tag name>', quantize=True)`

and ends up with the error 

`Traceback (most recent call last):
  File "espnet_onnx_export.py", line 7, in <module>
    from espnet_onnx.export import ASRModelExport
  File "/home/neso/espnet_onnx/espnet_onnx/export/__init__.py", line 1, in <module>
    from .asr.export_asr import ASRModelExport
  File "/home/neso/espnet_onnx/espnet_onnx/export/asr/export_asr.py", line 14, in <module>
    from espnet_model_zoo.downloader import ModelDownloader
  File "/home/neso/espnet_onnx/espnet_model_zoo.py", line 8, in <module>
    speech2text = Speech2Text.from_pretrained(
  File "/home/neso/anaconda3/envs/espnet_onnx/lib/python3.8/site-packages/espnet2/bin/asr_inference.py", line 556, in from_pretrained
    from espnet_model_zoo.downloader import ModelDownloader
ModuleNotFoundError: No module named 'espnet_model_zoo.downloader'; 'espnet_model_zoo' is not a package
`

**Comment by Masao-Someki** [comment]
Hi @neso613, please install `espnet_model_zoo`.
You can install it via `pip install espnet_model_zoo`
